fix updated metrics

diff --git a/.github/workflows/dev-metrics.yml b/.github/workflows/dev-metrics.yml
--- a/.github/workflows/dev-metrics.yml
+++ b/.github/workflows/dev-metrics.yml
@@ -11,18 +11,15 @@ jobs:
     permissions:
       contents: write
       pull-requests: write
-    steps:
 
+    steps:
       - name: Checkout existing metrics
         uses: actions/checkout@v4
         with:
           ref: inso-metrics
           fetch-depth: 0
           persist-credentials: true
-          path: metrics-branch   ## updated path
-
-      - name: Checkout Local Repo
-        uses: actions/checkout@v4
+          path: metrics-branch
 
       - name: Checkout INSO GH Metrics code
         uses: actions/checkout@v4
@@ -64,19 +61,19 @@ jobs:
           GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
           ORGANIZATION: ${{ github.repository_owner }}
 
-      - name: Move Generated Metrics to Metrics Branch ## updated
+      - name: Move Generated Metrics to Metrics Branch
         run: |
           mkdir -p metrics-branch/metrics
-          mv inso-gh-query-metrics/*${{ github.repository_owner }}.md metrics-branch/metrics/
+          mv inso-gh-query-metrics/*.md metrics-branch/metrics/
         shell: bash
 
       - name: Auto Commit Results
         uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: "[Automated] Milestone Metrics Update"
-          repository: metrics-branch ## here updated (commit inside that checkout)
+          repository: metrics-branch
           branch: inso-metrics
-          file_pattern: metrics/*.md
+          file_pattern: metrics/**/*.md
           commit_user_name: GitHub Action
           commit_user_email: action@github.com
           commit_author: GitHub Action <action@github.com>
@@ -84,11 +81,11 @@ jobs:
       - name: Create Pull Request
         run: |
           gh pr create \
-            --base ${{ github.ref }} \
+            --base main \
             --head "inso-metrics" \
             --title "[Automated] Milestone Metrics Update" \
             --body "This is an automated pull request to update the milestone metrics." \
-            --repo ${{ github.repository }} || echo "Command failed: Unable to create pull request. It might be due to the branch already existing or lack of permissions."
+            --repo ${{ github.repository }} || echo "Command failed: Unable to create pull request. It might be due to the PR already existing or lack of permissions."
         env:
           GH_TOKEN: ${{ github.token }}
         shell: bash
